@startuml

package ParkingLot {
	class ParkingLot <<Entity>> <<Aggregate>> {
	- int space
	- ParkingLotId id
	+void park(Car)
	+Car getBackCar(Car)
	}

	class Car <<VO>> {
	- String plateNumber
	}

	class Ticket <<VO>> {
	- ParkingLotId id
	- String validationNumber
	}

	Ticket *--> "1" Car
	ParkingLot o--> "*" Car
	ParkingLot o--> "*" Ticket
}

package ParkingBoy {
	interface ParkingStrategy <<VO>> {
	+ findAvailableParkingLot(List<ParkingLot>)
	}

	class ParkingBoy <<Entity>> <<Aggregate>> {
	- List<ParkingLotId> parkingLots
	+ ParkingLot findAvailableParkingLot()
	}

	ParkingBoy o--> "*" ParkingLot
	ParkingBoy o--> "1" ParkingStrategy
	ParkingStrategy <|.. NaturalParkingStrategy
	ParkingStrategy <|.. MaxSpaceFirstParkingStrategy

}

class ParkingManager <<DomainService>> {
+ Ticket park(Car)
+ Car getBackCar(Ticket)
}

ParkingManager .>  ParkingBoy
ParkingManager ..>  ParkingLot
ParkingManager ...>  Ticket



@enduml
